apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/open-policy-agent/gatekeeper-library/library/general/disallowedtags?ref=master
- github.com/open-policy-agent/gatekeeper-library/library/general/containerresources?ref=master
- github.com/open-policy-agent/gatekeeper-library/library/pod-security-policy/users?ref=master
- github.com/open-policy-agent/gatekeeper-library/library/pod-security-policy/host-network-ports?ref=master
